name: Test package

on: [push]

jobs:
  build:
    strategy:
      max-parallel: 16
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [2.7, 3.5, 3.6, 3.7]

    steps:
    - name: Checkout project 
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=lib
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude=lib
    - name: Install package 
      run: |
        python setup.py sdist > /dev/null
        pip install --verbose dist/*.tar.gz
    - name: Test with pytest
      run: |
        pip install pytest
        pytest tests -r a
