# pyvinecopulib documentation build configuration file.

import inspect
import os
import re
from typing import Any

import sphinx.ext.autodoc as autodoc
import sphinx.util.inspect as sphinxinspect
from sphinx.ext.autodoc import AttributeDocumenter, ModuleDocumenter

import pyvinecopulib as pv

# Monkey-patch sphinx's autodoc to recognize nanobind's nb_func as a routine.


def isnbfunc(obj: Any) -> bool:
  return (
    hasattr(type(obj), "__module__")
    and type(obj).__module__ == "nanobind"
    and type(obj).__name__ == "nb_func"
  )


def isfunction(obj: Any) -> bool:
  return inspect.isfunction(sphinxinspect.unpartial(obj)) or isnbfunc(obj)


def isroutine(obj: Any) -> bool:
  return inspect.isroutine(sphinxinspect.unpartial(obj)) or isnbfunc(obj)


sphinxinspect.isfunction = isfunction
sphinxinspect.isroutine = isroutine

assert autodoc.inspect.isfunction is isfunction
assert autodoc.inspect.isroutine is isroutine


@classmethod
def patched_can_document_member(
  cls, member: Any, membername: str, isattr: bool, parent: Any
) -> bool:
  if isinstance(parent, ModuleDocumenter):
    return False
  if sphinxinspect.isroutine(member):
    return False
  if sphinxinspect.isattributedescriptor(member):
    return True
  return not sphinxinspect.isroutine(member) and not isinstance(member, type)


AttributeDocumenter.can_document_member = patched_can_document_member

assert inspect.getsource(
  AttributeDocumenter.can_document_member
) == inspect.getsource(patched_can_document_member)


extensions = [
  "sphinx.ext.autodoc",
  "sphinx_autodoc_typehints",
  "sphinx.ext.githubpages",
  "sphinx.ext.intersphinx",
  "sphinx.ext.mathjax",
  "sphinx_rtd_theme",
  "sphinx.ext.autosummary",
  "numpydoc",
  "nbsphinx",
  "myst_parser",
]

# Resolve references to external Python libraries (e.g. ``numpy.ndarray``,
# ``torch.device`` / ``torch.dtype`` / ``torch.Tensor``, builtins like
# ``NotImplementedError``) against their published inventories, so signature
# annotations and cross-references to them render as links instead of dead
# monospace.
intersphinx_mapping = {
  "python": ("https://docs.python.org/3", None),
  "numpy": ("https://numpy.org/doc/stable", None),
  "torch": ("https://pytorch.org/docs/stable", None),
}

# numpydoc owns the Numpy-style section parser; we keep
# `sphinx_autodoc_typehints` alongside it for the type-from-annotation
# injection. The two settings below prevent typehints from emitting a
# separate `:rtype:` that would collide with numpydoc's inline rendering
# of the Returns type (mirrors what `napoleon_use_rtype = False` did
# under the old extension).
typehints_use_rtype = False
typehints_document_rtype = False


# Don't write a separate class-members toctree — render `__init__`
# content inside the class docstring instead (the closest equivalent of
# the old `napoleon_include_init_with_doc = True`).
numpydoc_class_members_toctree = False
# Don't synthesize a Notes / References / See Also section header when
# the docstring doesn't have one; we control that explicitly.
numpydoc_show_class_members = True
numpydoc_show_inherited_class_members = False
autosummary_generate = True
nbsphinx_execute = "never"

# `autosummary`: stub files don't exist on first toctree read (single-pass build).
# `myst.header`: index.rst inlines a slice of README.md starting at H2.
suppress_warnings = ["autosummary", "myst.header"]

# Fail the build on any unresolved cross-reference. Combined with the ``-W``
# already passed by ``make docs`` (and the ``verify_docs_build`` CI job), this
# is the gate that keeps documentation cross-references resolvable.
nitpicky = True

# The only references that cannot be resolved at the source:
# - ``pyvinecopulib.families.<family>`` — module-level aliases for
#   ``BicopFamily`` values, documented exhaustively on the ``families`` landing
#   page and the ``BicopFamily`` class, so they get no per-constant stub page.
# - ``Bicop.get_parameters_{lower,upper}_bounds`` / ``Bicop.flip`` — referenced
#   by upstream vinecopulib Doxygen under their C++ names; the Python binding
#   exposes the ``parameters_{lower,upper}_bounds`` properties instead (fix
#   belongs upstream, after which this entry can be dropped).
# - ``*.set_score_request`` — generated by scikit-learn's metadata-routing
#   machinery, not part of this project's API.
nitpick_ignore_regex = [
  (r"py:.*", r"pyvinecopulib\.families\.\w+"),
  (
    r"py:.*",
    r"pyvinecopulib\.core\.Bicop\.(get_parameters_(lower|upper)_bounds|flip)",
  ),
  # Upstream docstrings reference the C++ getter/setter names, but the binding
  # exposes them as the ``conditioning_set`` property.
  (
    r"py:.*",
    r"pyvinecopulib\.core\.FitControlsVinecop\.(get|set)_conditioning_set",
  ),
  (r"py:.*", r"pyvinecopulib\.sklearn\..*\.set_score_request"),
]


# Members inherited from sklearn / torch carry docstrings that
# :ref:/:term: into their own doc trees, which don't resolve in
# pyvinecopulib's build (sklearn) or have RST that numpydoc rejects
# (torch.nn.Module). Drop them — return None (not `skip`) for
# non-matching names because autosummary hard-codes `skip=False`
# when emitting this event, and a returned False would force-include
# otherwise-private members.
def _skip_inherited(app, what, name, obj, skip, options):
  mod = getattr(obj, "__module__", "")
  if isinstance(mod, str) and (
    mod.startswith("sklearn") or mod.startswith("torch")
  ):
    return True
  return None


source_suffix = {
  ".rst": "restructuredtext",
  ".md": "markdown",
}

templates_path = ["_templates"]
master_doc = "index"

# Don't exclude `_generate` — autosummary writes stubs there and sphinx
# reads them back as source documents.
# `releasing.md` is a maintainer checklist that lives next to the docs for
# discoverability, not a page of the user site.
exclude_patterns = ["_build", "**/.ipynb_checkpoints", "releasing.md"]

project = "pyvinecopulib"
copyright = "2024, Thomas Nagler and Thibault Vatter"
author = "Thomas Nagler and Thibault Vatter"

release = pv.__version__
version = ".".join(release.split(".")[:3])

# Don't set `html_extra_path = ["examples"]` — nbsphinx registers the
# staged notebooks as documents, and html_extra_path would shadow that.

html_theme = "sphinx_rtd_theme"

html_static_path = ["_static"]

html_copy_source = False

html_show_copyright = False

html_show_sphinx = False

add_module_names = False

pygments_style = "sphinx"

html_logo = "_static/pyvinecopulib.png"


# Each documented class maps to the subpackage it is documented under, so a
# backtick reference can be rewritten to a *fully-qualified* cross-reference
# target (``:class:`~pyvinecopulib.core.Vinecop```). Qualifying is what makes
# the link resolve from *any* page: an unqualified ``:class:`Vinecop``` only
# resolves on pages whose ``currentmodule`` already contains ``Vinecop`` (e.g.
# core pages), so a ``Vinecop`` reference inside a torch/sklearn docstring
# would otherwise render as dead monospace. The leading ``~`` keeps the
# rendered link text short (just the class name).
_CLASS_MODULE = {
  "BicopFamily": "pyvinecopulib.families",
  "BicopLike": "pyvinecopulib.core",
  "BicopBase": "pyvinecopulib.core",
  "MarginLike": "pyvinecopulib.core",
  "MarginBase": "pyvinecopulib.core",
  "Kde1dMargin": "pyvinecopulib.margins",
  "EmpiricalMargin": "pyvinecopulib.margins",
  "Bicop": "pyvinecopulib.core",
  "VinecopLike": "pyvinecopulib.core",
  "VinecopBase": "pyvinecopulib.core",
  "Vinecop": "pyvinecopulib.core",
  "CVineStructure": "pyvinecopulib.core",
  "DVineStructure": "pyvinecopulib.core",
  "RVineStructure": "pyvinecopulib.core",
  "ConditioningContext": "pyvinecopulib.core",
  "SimplifiedContext": "pyvinecopulib.core",
  "NonSimplifiedContext": "pyvinecopulib.core",
  "FitControlsBicop": "pyvinecopulib.core",
  "FitControlsVinecop": "pyvinecopulib.core",
  "Kde1d": "pyvinecopulib.utils",
  "VineDensity": "pyvinecopulib.sklearn",
  "VineRegressor": "pyvinecopulib.sklearn",
  "VinecopBackend": "pyvinecopulib.sklearn.backends",
  "TorchVinecopBackend": "pyvinecopulib.sklearn.backends",
  "TorchBicop": "pyvinecopulib.torch",
  "TorchVinecop": "pyvinecopulib.torch",
  "FitControlsTorchBicop": "pyvinecopulib.torch",
  "FitControlsTorchVinecop": "pyvinecopulib.torch",
}


def process_cross_references(content: str, is_docstring: bool = True) -> str:
  classes = list(_CLASS_MODULE)
  modules = [
    "pyvinecopulib.core",
    "pyvinecopulib.families",
    "pyvinecopulib.utils",
    "pyvinecopulib.margins",
    "pyvinecopulib.sklearn",
    "pyvinecopulib.sklearn.backends",
    "pyvinecopulib.torch",
  ]

  meth_ref = r":meth:`" if is_docstring else r"{py:meth}`"
  cls_ref = r":class:`" if is_docstring else r"{py:class}`"
  mod_ref = r":mod:`" if is_docstring else r"{py:mod}`"

  # Docstrings (RST) use double backticks; markdown sources use single.
  bt = "``" if is_docstring else "`"

  def _fqn(cls: str) -> str:
    return f"{_CLASS_MODULE[cls]}.{cls}"

  # Longest class name first so e.g. ``FitControlsTorchVinecop`` wins over
  # ``FitControlsVinecop`` and ``BicopBase`` over ``Bicop`` in the alternation.
  class_alt = "|".join(
    re.escape(c) for c in sorted(classes, key=len, reverse=True)
  )
  # ``Class.method()`` -> :meth:`~pkg.mod.Class.method`
  content = re.sub(
    rf"{bt}({class_alt})\.(\w+)\(\){bt}",
    lambda m: f"{meth_ref}~{_fqn(m.group(1))}.{m.group(2)}`",
    content,
  )
  # ``Class.attr`` -> :class:`~pkg.mod.Class.attr`
  content = re.sub(
    rf"{bt}({class_alt})\.(\w+){bt}",
    lambda m: f"{cls_ref}~{_fqn(m.group(1))}.{m.group(2)}`",
    content,
  )
  # bare ``Class`` -> :class:`~pkg.mod.Class`
  for cls in classes:
    content = re.sub(
      rf"{bt}{re.escape(cls)}{bt}", f"{cls_ref}~{_fqn(cls)}`", content
    )
  # Module references — longest-prefix first so `pyvinecopulib.sklearn.backends`
  # wins over `pyvinecopulib.sklearn`.
  for mod in sorted(modules, key=len, reverse=True):
    content = re.sub(rf"{bt}{re.escape(mod)}{bt}", rf"{mod_ref}{mod}`", content)

  return content


def autodoc_process_docstring(app, what, name, obj, options, lines):
  docstring = process_cross_references("\n".join(lines))
  lines.clear()
  lines.extend(docstring.splitlines())


_NB_ARRAY_RE = re.compile(r"numpy\.ndarray\[[^\]]*\]")


def autodoc_process_signature(
  app, what, name, obj, options, signature, return_annotation
):
  # nanobind embeds array parameters in the signature as
  # ``numpy.ndarray[dtype=..., shape=..., order=...]`` (a form intersphinx
  # can't resolve). Collapse to the resolvable ``numpy.ndarray``; the precise
  # shape / dtype is documented in the numpydoc Parameters/Returns type strings.
  def _fix(s):
    return _NB_ARRAY_RE.sub("numpy.ndarray", s) if s else s

  return _fix(signature), _fix(return_annotation)


def preprocess_markdown(app, docname, source):
  if docname in {"CHANGELOG", "README"}:
    source[0] = (
      "```{eval-rst}\n.. currentmodule:: pyvinecopulib\n```\n" + source[0]
    )
    source[0] = process_cross_references(source[0], is_docstring=False)


# Stage README/CHANGELOG/CONTRIBUTING/examples into the docs source tree and
# write features.rst / examples.rst toctrees so plain `sphinx-build` works.
# Documentation references the canonical pyvinecopulib.<subpkg>.<name>;
# top-level aliases still resolve but aren't documented.
DOCSTRING_SUBPACKAGES = {
  "core": {
    "classes": [
      "Bicop",
      "BicopLike",
      "BicopBase",
      "FitControlsBicop",
      "Vinecop",
      "VinecopLike",
      "VinecopBase",
      "FitControlsVinecop",
      "CVineStructure",
      "DVineStructure",
      "RVineStructure",
      "ConditioningContext",
      "SimplifiedContext",
      "NonSimplifiedContext",
      "MarginLike",
      "MarginBase",
    ],
    "functions": [],
  },
  "families": {
    "classes": ["BicopFamily"],
    "functions": [],
  },
  "utils": {
    "classes": ["Kde1d"],
    "functions": [
      "to_pseudo_obs",
      "simulate_uniform",
      "wdm",
      "ghalton",
      "sobol",
      "pairs_copula_data",
      "benchmark",
    ],
  },
  "margins": {
    "classes": [
      "Kde1dMargin",
      "EmpiricalMargin",
    ],
    "functions": [
      "as_margin",
      "register_margin_adapter",
    ],
  },
  "sklearn": {
    "classes": [
      "VineDensity",
      "VineRegressor",
    ],
    "functions": [],
  },
  "sklearn.backends": {
    "classes": [
      "VinecopBackend",
      "TorchVinecopBackend",
    ],
    "functions": ["resolve_backend"],
  },
  "torch": {
    "classes": [
      "TorchBicop",
      "TorchVinecop",
      "FitControlsTorchBicop",
      "FitControlsTorchVinecop",
    ],
    "functions": [],
  },
}

DOCSTRING_CLASSES = [
  cls for sub in DOCSTRING_SUBPACKAGES.values() for cls in sub["classes"]
]
DOCSTRING_FUNCTIONS = [
  fn for sub in DOCSTRING_SUBPACKAGES.values() for fn in sub["functions"]
]


def _stage_repo_files(docs_dir, repo_root):
  """Symlink (or copy on Windows) repo-root files into the docs source dir."""
  import shutil

  to_stage = ["README.md", "examples", "CHANGELOG.md"]
  for name in to_stage:
    src = os.path.join(repo_root, name)
    dst = os.path.join(docs_dir, name)
    if os.path.lexists(dst):
      continue
    try:
      os.symlink(src, dst)
    except (OSError, NotImplementedError):
      if os.path.isdir(src):
        shutil.copytree(src, dst)
      else:
        shutil.copy2(src, dst)

  # index.rst inlines README.md via `.. include:: README.md`, which
  # bypasses the `source-read` event — so the standalone README page
  # picks up cross-references via preprocess_markdown, but the inlined
  # landing-page copy does not. Materialize a rewritten copy here at
  # configure time so both rendered pages stay in sync.
  readme_src = os.path.join(docs_dir, "README.md")
  readme_inlined = os.path.join(docs_dir, "_README_inlined.md")
  if os.path.isfile(readme_src):
    readme = open(readme_src).read()
    readme = process_cross_references(readme, is_docstring=False)
    # Drop the first 8 lines (title + badges) — matches the historical
    # `.. include:: README.md :start-line: 8`.
    readme = "\n".join(readme.splitlines()[8:])
    with open(readme_inlined, "w") as f:
      f.write("```{eval-rst}\n.. currentmodule:: pyvinecopulib\n```\n")
      f.write(readme)


def _write_features_rst(out_path):
  """Generate API documentation RST: one section per subpackage."""
  rst_name = "API Documentation"
  bar = "=" * len(rst_name)
  with open(out_path, "w") as f:
    f.write(".. GENERATED FILE DO NOT EDIT\n\n")
    f.write(f"{bar}\n{rst_name}\n{bar}\n\n")
    for subpkg, contents in DOCSTRING_SUBPACKAGES.items():
      module = f"pyvinecopulib.{subpkg}"
      header = f"``{module}``"
      f.write(f"{header}\n{'-' * len(header)}\n\n")
      f.write(f".. automodule:: {module}\n\n")
      classes = contents.get("classes", [])
      if classes:
        f.write("Classes\n^^^^^^^\n\n")
        f.write(".. autosummary::\n    :toctree: _generate\n\n")
        for cls in classes:
          f.write(f"    {module}.{cls}\n")
        f.write("\n")
      functions = contents.get("functions", [])
      if functions:
        f.write("Functions\n^^^^^^^^^\n\n")
        f.write(".. autosummary::\n    :toctree: _generate\n\n")
        for fn in functions:
          f.write(f"    {module}.{fn}\n")
        f.write("\n")


def _write_examples_rst(out_path, examples_dir):
  """Generate the toctree linking to all example notebooks."""
  if not os.path.isdir(examples_dir):
    return
  notebooks = sorted(
    f for f in os.listdir(examples_dir) if f.endswith(".ipynb")
  )
  if not notebooks:
    return
  with open(out_path, "w") as f:
    f.write("Examples\n========\n\n")
    f.write(
      "The following example notebooks are included in this documentation:\n\n"
    )
    f.write(".. toctree::\n   :maxdepth: 1\n   :titlesonly:\n\n")
    for nb in notebooks:
      f.write(f"   examples/{os.path.splitext(nb)[0]}\n")


# Stage docs and write features.rst / examples.rst at conf.py load time.
# Must be eager (not `builder-inited`), otherwise it races with autosummary's
# stub generation and the per-class pages never render on a single-pass build.
_DOCS_DIR = os.path.dirname(os.path.abspath(__file__))
_REPO_ROOT = os.path.dirname(_DOCS_DIR)
_stage_repo_files(_DOCS_DIR, _REPO_ROOT)
_write_features_rst(os.path.join(_DOCS_DIR, "features.rst"))
_write_examples_rst(
  os.path.join(_DOCS_DIR, "examples.rst"),
  os.path.join(_DOCS_DIR, "examples"),
)


def setup(app):
  app.connect("autodoc-process-docstring", autodoc_process_docstring)
  app.connect("autodoc-process-signature", autodoc_process_signature)
  app.connect("source-read", preprocess_markdown)
  app.connect("autodoc-skip-member", _skip_inherited)


source_suffix = {
  ".rst": "restructuredtext",
  ".md": "markdown",
}
