# pyvinecopulib documentation build configuration file.

import inspect
import os
import re
from typing import Any

import sphinx.ext.autodoc as autodoc
import sphinx.util.inspect as sphinxinspect
from sphinx.ext.autodoc import AttributeDocumenter, ModuleDocumenter

import pyvinecopulib as pv

# Monkey-patch sphinx's autodoc to recognize nanobind's nb_func as a routine.


def isnbfunc(obj: Any) -> bool:
  return (
    hasattr(type(obj), "__module__")
    and type(obj).__module__ == "nanobind"
    and type(obj).__name__ == "nb_func"
  )


def isfunction(obj: Any) -> bool:
  return inspect.isfunction(sphinxinspect.unpartial(obj)) or isnbfunc(obj)


def isroutine(obj: Any) -> bool:
  return inspect.isroutine(sphinxinspect.unpartial(obj)) or isnbfunc(obj)


sphinxinspect.isfunction = isfunction
sphinxinspect.isroutine = isroutine

assert autodoc.inspect.isfunction is isfunction
assert autodoc.inspect.isroutine is isroutine


@classmethod
def patched_can_document_member(
  cls, member: Any, membername: str, isattr: bool, parent: Any
) -> bool:
  if isinstance(parent, ModuleDocumenter):
    return False
  if sphinxinspect.isroutine(member):
    return False
  if sphinxinspect.isattributedescriptor(member):
    return True
  return not sphinxinspect.isroutine(member) and not isinstance(member, type)


AttributeDocumenter.can_document_member = patched_can_document_member

assert inspect.getsource(
  AttributeDocumenter.can_document_member
) == inspect.getsource(patched_can_document_member)


extensions = [
  "sphinx.ext.autodoc",
  "sphinx_autodoc_typehints",
  "sphinx.ext.githubpages",
  "sphinx.ext.intersphinx",
  "sphinx.ext.mathjax",
  "sphinx_rtd_theme",
  "sphinx.ext.autosummary",
  "numpydoc",
  "nbsphinx",
  "myst_parser",
]

# External types in signatures and cross-references render as links rather
# than dead monospace.
intersphinx_mapping = {
  "python": ("https://docs.python.org/3", None),
  "numpy": ("https://numpy.org/doc/stable", None),
  "torch": ("https://pytorch.org/docs/stable", None),
  # For the `DataFrame` alias below: the sklearn lane accepts one, and its
  # docstrings name the type unqualified.
  "pandas": ("https://pandas.pydata.org/docs", None),
}

# numpydoc renders the Returns type inline, so a separate `:rtype:` from
# sphinx_autodoc_typehints would collide with it.
typehints_use_rtype = False
typehints_document_rtype = False


# Don't write a separate class-members toctree — render `__init__`
# content inside the class docstring instead (the closest equivalent of
# the old `napoleon_include_init_with_doc = True`).
numpydoc_class_members_toctree = False
# Don't synthesize a Notes / References / See Also section header when
# the docstring doesn't have one; we control that explicitly.
numpydoc_show_class_members = True
numpydoc_show_inherited_class_members = False
autosummary_generate = True
nbsphinx_execute = "never"

# `autosummary`: stub files don't exist on first toctree read (single-pass build).
# `myst.header`: index.rst inlines a slice of README.md starting at H2.
suppress_warnings = ["autosummary", "myst.header"]

# Fail the build on any unresolved cross-reference. Combined with the ``-W``
# already passed by ``make docs`` (and the ``verify_docs_build`` CI job), this
# is the gate that keeps documentation cross-references resolvable.
nitpicky = True

# References with no target to fix. The family aliases are documented on the
# `families` page rather than per constant; the `Bicop` getter names come from
# upstream Doxygen and retire when upstream renames them; `set_score_request`
# is generated by scikit-learn.
nitpick_ignore_regex = [
  (r"py:.*", r"pyvinecopulib\.families\.\w+"),
  (
    r"py:.*",
    r"pyvinecopulib\.core\.Bicop\.(get_parameters_(lower|upper)_bounds|flip)",
  ),
  # Upstream docstrings reference the C++ getter/setter names, but the binding
  # exposes them as the ``conditioning_set`` property.
  (
    r"py:.*",
    r"pyvinecopulib\.core\.FitControlsVinecop\.(get|set)_conditioning_set",
  ),
  (r"py:.*", r"pyvinecopulib\.sklearn\..*\.set_score_request"),
  # The `bicop_class` / `vinecop_class` / `margin_class` declarations name the
  # class a base fits, so the attribute's *value* is a class. autosummary
  # treats that as a re-exported class rather than an attribute and generates
  # no stub, so the Attributes entry a subclass inherits has nothing to point
  # at. Retires when autosummary can page a class-valued attribute; the
  # declarations are documented in their owners' class docstrings meanwhile.
  (
    r"py:obj",
    r"pyvinecopulib\.\w+\.\w+\.(bicop|vinecop|margin)_class",
  ),
  # The structural Protocols that type an unimported ecosystem's objects --
  # `margins/openturns.py`'s `_Distribution`, `_Factory` and their kin. Neither
  # SciPy nor OpenTURNS ships `py.typed`, and `scipy-stubs` needs Python 3.12
  # against this project's 3.11 floor, so a Protocol naming exactly the members
  # the code calls is what types those boundaries. They are private, so
  # autosummary generates no page for them to point at, while the numpydoc
  # `Returns` beside each says the ecosystem type a reader wants
  # (`openturns.Distribution`). Retires if either library ships types.
  (r"py:.*", r"pyvinecopulib\.\w+\.\w+\._[A-Z]\w+"),
  # `ArrayT` is the TypeVar the array-agnostic contracts are generic over. It
  # appears in rendered signatures wherever one is parameterized, and a
  # TypeVar has no page of its own to link to.
  (r"py:class", r"pyvinecopulib\.core\.protocols\.ArrayT"),
]


# Members inherited from sklearn / torch reference their own doc trees, which
# do not resolve here. Returns `None` rather than `skip` for a non-match:
# autosummary hard-codes `skip=False`, so returning it would force-include
# otherwise-private members.
def _skip_inherited(app, what, name, obj, skip, options):
  mod = getattr(obj, "__module__", "")
  if isinstance(mod, str) and (
    mod.startswith("sklearn") or mod.startswith("torch")
  ):
    return True
  return None


source_suffix = {
  ".rst": "restructuredtext",
  ".md": "markdown",
}

templates_path = ["_templates"]
master_doc = "index"

# `_generate` is not excluded: autosummary writes stubs there and sphinx reads
# them back. `releasing.md` is a maintainer checklist, and `README.md` is
# staged only so `_README_inlined.md` can be derived from it.
exclude_patterns = [
  "_build",
  "**/.ipynb_checkpoints",
  "releasing.md",
  "README.md",
]

project = "pyvinecopulib"
copyright = "2024, Thomas Nagler and Thibault Vatter"
author = "Thomas Nagler and Thibault Vatter"

release = pv.__version__
version = ".".join(release.split(".")[:3])

# Don't set `html_extra_path = ["examples"]` — nbsphinx registers the
# staged notebooks as documents, and html_extra_path would shadow that.

html_theme = "sphinx_rtd_theme"

html_static_path = ["_static"]

html_copy_source = False

html_show_copyright = False

html_show_sphinx = False

add_module_names = False

pygments_style = "sphinx"

html_logo = "_static/pyvinecopulib.png"


# Each documented class to the subpackage it is documented under, so a
# backtick reference becomes a fully-qualified target. Qualifying is what makes
# it resolve from any page: an unqualified `:class:`Vinecop`` resolves only
# where `currentmodule` already contains it. The leading `~` keeps the rendered
# text to the class name.
_CLASS_MODULE = {
  "BicopFamily": "pyvinecopulib.families",
  "BicopLike": "pyvinecopulib.core",
  "BicopBase": "pyvinecopulib.core",
  "MarginLike": "pyvinecopulib.core",
  "MarginBase": "pyvinecopulib.core",
  "OpenTURNSMargin": "pyvinecopulib.margins",
  "SciPyMargin": "pyvinecopulib.margins",
  "FitControlsMargin": "pyvinecopulib.core",
  "Bicop": "pyvinecopulib.core",
  "VinecopLike": "pyvinecopulib.core",
  "VinecopBase": "pyvinecopulib.core",
  "Vinecop": "pyvinecopulib.core",
  "Vinedist": "pyvinecopulib.core",
  "CVineStructure": "pyvinecopulib.core",
  "DVineStructure": "pyvinecopulib.core",
  "RVineStructure": "pyvinecopulib.core",
  "ConditioningContext": "pyvinecopulib.core",
  "SimplifiedContext": "pyvinecopulib.core",
  "NonSimplifiedContext": "pyvinecopulib.core",
  "FitControlsBicop": "pyvinecopulib.core",
  "FitControlsVinecop": "pyvinecopulib.core",
  "Kde1d": "pyvinecopulib.core",
  "VineDensity": "pyvinecopulib.sklearn",
  "VineRegressor": "pyvinecopulib.sklearn",
  "VinecopBackend": "pyvinecopulib.sklearn.backends",
  "TorchVinecopBackend": "pyvinecopulib.sklearn.backends",
  "TorchTllBicop": "pyvinecopulib.torch",
  "TorchKde1d": "pyvinecopulib.torch",
  "TorchDistributionMargin": "pyvinecopulib.torch",
  "TorchVinecop": "pyvinecopulib.torch",
  "TorchVinedist": "pyvinecopulib.torch",
  "FitControlsTorchBicop": "pyvinecopulib.torch",
  "FitControlsTorchVinecop": "pyvinecopulib.torch",
  "ControlsLike": "pyvinecopulib.core",
  "DiscretePair": "pyvinecopulib.core",
  "IndependencePair": "pyvinecopulib.core",
  "VinedistLike": "pyvinecopulib.core",
  "VinedistBase": "pyvinecopulib.core",
}

#: The documented *functions*, which need ``:func:`` rather than ``:class:``.
#: Kept apart from ``_CLASS_MODULE`` for that reason alone; both feed
#: ``numpydoc_xref_aliases`` below.
_FUNCTION_MODULE = {
  "margin_from_json": "pyvinecopulib.core",
  "margin_to_json": "pyvinecopulib.core",
  "register_margin_json": "pyvinecopulib.core",
  "as_margin": "pyvinecopulib.margins",
  "register_margin_adapter": "pyvinecopulib.margins",
  "resolve_margins": "pyvinecopulib.margins",
  "resolve_margin_controls": "pyvinecopulib.margins",
  "to_pseudo_obs": "pyvinecopulib.utils",
  "sample_uniform": "pyvinecopulib.utils",
  "wdm": "pyvinecopulib.utils",
  "find_latent_sample": "pyvinecopulib.utils",
  "ghalton": "pyvinecopulib.utils",
  "sobol": "pyvinecopulib.utils",
  "pairs_copula_data": "pyvinecopulib.utils",
}


#: Link documented names in a numpydoc type field, with the alias table
#: derived from the dicts above so a name cannot be linked in prose and dead
#: in a type field. ``"all"`` leaves every other token alone, which is what
#: keeps the shape grammar out of the nitpicky build's way.
numpydoc_xref_param_type = True
numpydoc_xref_ignore = "all"
numpydoc_xref_aliases = {
  **{name: f"{mod}.{name}" for name, mod in _CLASS_MODULE.items()},
  **{name: f"{mod}.{name}" for name, mod in _FUNCTION_MODULE.items()},
  # The two array types the package names unqualified, plus the pandas one.
  "Tensor": "torch.Tensor",
  "ndarray": "numpy.ndarray",
  "DataFrame": "pandas.DataFrame",
}


def process_cross_references(content: str, is_docstring: bool = True) -> str:
  classes = list(_CLASS_MODULE)
  modules = [
    "pyvinecopulib.core",
    "pyvinecopulib.families",
    "pyvinecopulib.utils",
    "pyvinecopulib.margins",
    "pyvinecopulib.sklearn",
    "pyvinecopulib.sklearn.backends",
    "pyvinecopulib.torch",
  ]

  meth_ref = r":meth:`" if is_docstring else r"{py:meth}`"
  cls_ref = r":class:`" if is_docstring else r"{py:class}`"
  mod_ref = r":mod:`" if is_docstring else r"{py:mod}`"
  func_ref = r":func:`" if is_docstring else r"{py:func}`"

  # Docstrings (RST) use double backticks; markdown sources use single.
  bt = "``" if is_docstring else "`"

  def _fqn(cls: str) -> str:
    return f"{_CLASS_MODULE[cls]}.{cls}"

  # Longest class name first so e.g. ``FitControlsTorchVinecop`` wins over
  # ``FitControlsVinecop`` and ``BicopBase`` over ``Bicop`` in the alternation.
  class_alt = "|".join(
    re.escape(c) for c in sorted(classes, key=len, reverse=True)
  )
  # ``Class.method()`` -> :meth:`~pkg.mod.Class.method`
  content = re.sub(
    rf"{bt}({class_alt})\.(\w+)\(\){bt}",
    lambda m: f"{meth_ref}~{_fqn(m.group(1))}.{m.group(2)}`",
    content,
  )
  # ``Class.attr`` -> :class:`~pkg.mod.Class.attr`
  content = re.sub(
    rf"{bt}({class_alt})\.(\w+){bt}",
    lambda m: f"{cls_ref}~{_fqn(m.group(1))}.{m.group(2)}`",
    content,
  )
  # ``Class()`` -> :class:`~pkg.mod.Class`, the constructor-call spelling.
  # Written before the bare form, which would otherwise leave the parentheses
  # outside the role and render them as literal text.
  content = re.sub(
    rf"{bt}({class_alt})\(\){bt}",
    lambda m: f"{cls_ref}~{_fqn(m.group(1))}`",
    content,
  )
  # bare ``Class`` -> :class:`~pkg.mod.Class`
  for cls in classes:
    content = re.sub(
      rf"{bt}{re.escape(cls)}{bt}", f"{cls_ref}~{_fqn(cls)}`", content
    )
  # bare ``function`` -> :func:`~pkg.mod.function`
  for func, mod in _FUNCTION_MODULE.items():
    content = re.sub(
      rf"{bt}{re.escape(func)}{bt}", f"{func_ref}~{mod}.{func}`", content
    )
  # Module references — longest-prefix first so `pyvinecopulib.sklearn.backends`
  # wins over `pyvinecopulib.sklearn`.
  for mod in sorted(modules, key=len, reverse=True):
    content = re.sub(rf"{bt}{re.escape(mod)}{bt}", rf"{mod_ref}{mod}`", content)

  return content


def autodoc_process_docstring(app, what, name, obj, options, lines):
  docstring = process_cross_references("\n".join(lines))
  lines.clear()
  lines.extend(docstring.splitlines())


_NB_ARRAY_RE = re.compile(r"numpy\.ndarray\[[^\]]*\]")


def autodoc_process_signature(
  app, what, name, obj, options, signature, return_annotation
):
  # nanobind embeds array parameters in the signature as
  # ``numpy.ndarray[dtype=..., shape=..., order=...]`` (a form intersphinx
  # can't resolve). Collapse to the resolvable ``numpy.ndarray``; the precise
  # shape / dtype is documented in the numpydoc Parameters/Returns type strings.
  def _fix(s):
    return _NB_ARRAY_RE.sub("numpy.ndarray", s) if s else s

  return _fix(signature), _fix(return_annotation)


def preprocess_markdown(app, docname, source):
  if docname in {"CHANGELOG", "README"}:
    source[0] = (
      "```{eval-rst}\n.. currentmodule:: pyvinecopulib\n```\n" + source[0]
    )
    source[0] = process_cross_references(source[0], is_docstring=False)


# Stage README/CHANGELOG/CONTRIBUTING/examples into the docs source tree and
# write features.rst / examples.rst toctrees so plain `sphinx-build` works.
# Documentation references the canonical pyvinecopulib.<subpkg>.<name>;
# top-level aliases still resolve but aren't documented.
DOCSTRING_SUBPACKAGES = {
  "core": {
    "classes": [
      "Bicop",
      "BicopFamily",
      "Kde1d",
      "BicopLike",
      "BicopBase",
      "FitControlsBicop",
      "Vinecop",
      "VinecopLike",
      "VinecopBase",
      "FitControlsVinecop",
      "FitControlsMargin",
      "CVineStructure",
      "DVineStructure",
      "RVineStructure",
      "ConditioningContext",
      "SimplifiedContext",
      "NonSimplifiedContext",
      "DiscretePair",
      "IndependencePair",
      "MarginLike",
      "MarginBase",
      "Vinedist",
      "VinedistLike",
      "VinedistBase",
      "ControlsLike",
    ],
    "functions": [
      "margin_from_json",
      "margin_to_json",
      "register_margin_json",
    ],
  },
  "families": {
    "classes": ["BicopFamily"],
    "functions": [],
  },
  "utils": {
    "classes": [],
    "functions": [
      "to_pseudo_obs",
      "sample_uniform",
      "wdm",
      "find_latent_sample",
      "ghalton",
      "sobol",
      "pairs_copula_data",
    ],
  },
  "margins": {
    # `FitControlsMargin` is re-exported here and documented under `core`,
    # which owns it: autosummary generates one page per (module, name), so a
    # name in two `__all__`s must be listed once, and
    # `process_cross_references` resolves the bare name to `core`.
    "classes": [
      "SciPyMargin",
      "OpenTURNSMargin",
    ],
    "functions": [
      "as_margin",
      "register_margin_adapter",
      "resolve_margins",
      "resolve_margin_controls",
    ],
  },
  "sklearn": {
    "classes": [
      "VineDensity",
      "VineRegressor",
    ],
    "functions": [],
  },
  "sklearn.backends": {
    "classes": [
      "VinecopBackend",
      "TorchVinecopBackend",
    ],
    "functions": ["resolve_backend"],
  },
  "torch": {
    "classes": [
      "TorchTllBicop",
      "TorchKde1d",
      "TorchDistributionMargin",
      "TorchVinecop",
      "TorchVinedist",
      "FitControlsTorchBicop",
      "FitControlsTorchVinecop",
    ],
    "functions": [],
  },
}

DOCSTRING_CLASSES = [
  cls for sub in DOCSTRING_SUBPACKAGES.values() for cls in sub["classes"]
]
DOCSTRING_FUNCTIONS = [
  fn for sub in DOCSTRING_SUBPACKAGES.values() for fn in sub["functions"]
]


def _stage_repo_files(docs_dir, repo_root):
  """Symlink (or copy on Windows) repo-root files into the docs source dir."""
  import shutil

  to_stage = ["README.md", "examples", "CHANGELOG.md"]
  for name in to_stage:
    src = os.path.join(repo_root, name)
    dst = os.path.join(docs_dir, name)
    if os.path.lexists(dst):
      continue
    try:
      os.symlink(src, dst)
    except (OSError, NotImplementedError):
      if os.path.isdir(src):
        shutil.copytree(src, dst)
      else:
        shutil.copy2(src, dst)

  # index.rst inlines README.md via `.. include:: README.md`, which
  # bypasses the `source-read` event — so the standalone README page
  # picks up cross-references via preprocess_markdown, but the inlined
  # landing-page copy does not. Materialize a rewritten copy here at
  # configure time so both rendered pages stay in sync.
  readme_src = os.path.join(docs_dir, "README.md")
  readme_inlined = os.path.join(docs_dir, "_README_inlined.md")
  if os.path.isfile(readme_src):
    readme = open(readme_src).read()
    readme = process_cross_references(readme, is_docstring=False)
    # Drop the first 8 lines (title + badges) — matches the historical
    # `.. include:: README.md :start-line: 8`.
    readme = "\n".join(readme.splitlines()[8:])
    with open(readme_inlined, "w") as f:
      f.write("```{eval-rst}\n.. currentmodule:: pyvinecopulib\n```\n")
      f.write(readme)


def _write_features_rst(out_path):
  """Generate API documentation RST: one section per subpackage."""
  rst_name = "API Documentation"
  bar = "=" * len(rst_name)
  with open(out_path, "w") as f:
    f.write(".. GENERATED FILE DO NOT EDIT\n\n")
    f.write(f"{bar}\n{rst_name}\n{bar}\n\n")
    for subpkg, contents in DOCSTRING_SUBPACKAGES.items():
      module = f"pyvinecopulib.{subpkg}"
      header = f"``{module}``"
      f.write(f"{header}\n{'-' * len(header)}\n\n")
      f.write(f".. automodule:: {module}\n\n")
      classes = contents.get("classes", [])
      if classes:
        f.write("Classes\n^^^^^^^\n\n")
        f.write(".. autosummary::\n    :toctree: _generate\n\n")
        for cls in classes:
          f.write(f"    {module}.{cls}\n")
        f.write("\n")
      functions = contents.get("functions", [])
      if functions:
        f.write("Functions\n^^^^^^^^^\n\n")
        f.write(".. autosummary::\n    :toctree: _generate\n\n")
        for fn in functions:
          f.write(f"    {module}.{fn}\n")
        f.write("\n")


def _write_examples_rst(out_path, examples_dir):
  """Generate the toctree linking to all example notebooks."""
  if not os.path.isdir(examples_dir):
    return
  notebooks = sorted(
    f for f in os.listdir(examples_dir) if f.endswith(".ipynb")
  )
  if not notebooks:
    return
  with open(out_path, "w") as f:
    f.write("Examples\n========\n\n")
    f.write(
      "The following example notebooks are included in this documentation:\n\n"
    )
    f.write(".. toctree::\n   :maxdepth: 1\n   :titlesonly:\n\n")
    for nb in notebooks:
      f.write(f"   examples/{os.path.splitext(nb)[0]}\n")


# Stage docs and write features.rst / examples.rst at conf.py load time.
# Must be eager (not `builder-inited`), otherwise it races with autosummary's
# stub generation and the per-class pages never render on a single-pass build.
_DOCS_DIR = os.path.dirname(os.path.abspath(__file__))
_REPO_ROOT = os.path.dirname(_DOCS_DIR)
_stage_repo_files(_DOCS_DIR, _REPO_ROOT)
_write_features_rst(os.path.join(_DOCS_DIR, "features.rst"))
_write_examples_rst(
  os.path.join(_DOCS_DIR, "examples.rst"),
  os.path.join(_DOCS_DIR, "examples"),
)


def setup(app):
  app.connect("autodoc-process-docstring", autodoc_process_docstring)
  app.connect("autodoc-process-signature", autodoc_process_signature)
  app.connect("source-read", preprocess_markdown)
  app.connect("autodoc-skip-member", _skip_inherited)


source_suffix = {
  ".rst": "restructuredtext",
  ".md": "markdown",
}
