package:
  name: pyvinecopulib
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'dev') }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}
  script_env:
    - CC
    - CXX

source:
  git_url: ../

requirements:
  build:
    - python
    - numpy >=1.14
    - setuptools
    - pybind11
    - cmake

  run:
    - python
    - numpy
    - vs2015_runtime  # [win]

test:
  imports:
    - numpy
    - pyvinecopulib
  requires:
    - pytest
  commands:
    - py.test pyvinecopulib


about:
  summary: A python interface to vinecopulib.
  license_file: LICENSE
